### ISSUE TITLE
non NCName

### ISSUE THREAD

**Issue by menzowindhouwer** [CLARIAH/codemeta-lod-to-cmdi#1]
the conversion currently results in non well formed XML if the JSON uses non NC names as field names. To be solved by storing the original name in an `@org` and using the last part as the element name.

`"og:image": "https://www.repostatus.org/badges/latest/active.svg"`
into
`
<cmdp:image org="og:image">https://www.repostatus.org/badges/latest/active.svg</cmdp:image>
`
and
`
"https://github.com/proycon/codemetapy/errors": 0
`
into
`
<cmdp:errors org="https://github.com/proycon/codemetapy/errors">0</cmdp:errors>
`

**Comment by MKroese** [comment]
Second one (with the urls) is fixed.
First one (with : in the tagname): the attribute org 'climbs up' to the higher levels... Another fix is needed.

**Comment by MKroese** [comment]
Problem with : in tags solved.
